/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_wwc2_jni_avinsignal_AvinSignalNative.h"


/*
 * Class:     com_wwc2_jni_avinsignal_AvinSignalNative
 * Method:    AVINSIGNAL_read
 * Signature: ()I
 */

JNIEXPORT jint JNICALL Java_com_wwc2_jni_avinsignal_AvinSignalNative_AVINSIGNAL_1read
  (JNIEnv *env, jclass obj){
  jint i=1;
  return i;

}
