/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wwc2_jni_micswitch_MicSwitchNative */

#ifndef _Included_com_wwc2_jni_micswitch_MicSwitchNative
#define _Included_com_wwc2_jni_micswitch_MicSwitchNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wwc2_jni_micswitch_MicSwitchNative
 * Method:    MICSWITCH_ARM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_micswitch_MicSwitchNative_MICSWITCH_1ARM
  (JNIEnv *, jclass);

/*
 * Class:     com_wwc2_jni_micswitch_MicSwitchNative
 * Method:    MICSWITCH_BT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_micswitch_MicSwitchNative_MICSWITCH_1BT
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
