/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wwc2_jni_camera_CameraNative */

#ifndef _Included_com_wwc2_jni_camera_CameraNative
#define _Included_com_wwc2_jni_camera_CameraNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wwc2_jni_camera_CameraNative
 * Method:    CAMERA_read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_camera_CameraNative_CAMERA_1read
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
