/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wwc2_jni_tp_touch_TPTouchNative */

#ifndef _Included_com_wwc2_jni_tp_touch_TPTouchNative
#define _Included_com_wwc2_jni_tp_touch_TPTouchNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wwc2_jni_tp_touch_TPTouchNative
 * Method:    TP_positionX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_tp_1touch_TPTouchNative_TP_1positionX
  (JNIEnv *, jclass);

/*
 * Class:     com_wwc2_jni_tp_touch_TPTouchNative
 * Method:    TP_positionY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_tp_1touch_TPTouchNative_TP_1positionY
  (JNIEnv *, jclass);

/*
 * Class:     com_wwc2_jni_tp_touch_TPTouchNative
 * Method:    TP_positionRect
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_tp_1touch_TPTouchNative_TP_1positionRect
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
