/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wwc2_jni_simulate_key_SimulateKeyNative */

#ifndef _Included_com_wwc2_jni_simulate_key_SimulateKeyNative
#define _Included_com_wwc2_jni_simulate_key_SimulateKeyNative
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_HOME
#define com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_HOME 102L
#undef com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_MENU
#define com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_MENU 139L
#undef com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_BACK
#define com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_BACK 158L
#undef com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_NEXT
#define com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_NEXT 163L
#undef com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_PREV
#define com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_PREV 165L
#undef com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_PLAY_PAUSE
#define com_wwc2_jni_simulate_key_SimulateKeyNative_VR_KEY_CODE_PLAY_PAUSE 164L
/*
 * Class:     com_wwc2_jni_simulate_key_SimulateKeyNative
 * Method:    SIMULATE_key
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_simulate_1key_SimulateKeyNative_SIMULATE_1key
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
