/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wwc2_jni_backlight_BacklightNative */

#ifndef _Included_com_wwc2_jni_backlight_BacklightNative
#define _Included_com_wwc2_jni_backlight_BacklightNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wwc2_jni_backlight_BacklightNative
 * Method:    BACKLIGHT_open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_backlight_BacklightNative_BACKLIGHT_1open
  (JNIEnv *, jclass);

/*
 * Class:     com_wwc2_jni_backlight_BacklightNative
 * Method:    BACKLIGHT_read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_backlight_BacklightNative_BACKLIGHT_1read
  (JNIEnv *, jclass);

/*
 * Class:     com_wwc2_jni_backlight_BacklightNative
 * Method:    BACKLIGHT_close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_backlight_BacklightNative_BACKLIGHT_1close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
