/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wwc2_jni_deepsleep_DeepSleepNative */

#ifndef _Included_com_wwc2_jni_deepsleep_DeepSleepNative
#define _Included_com_wwc2_jni_deepsleep_DeepSleepNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wwc2_jni_deepsleep_DeepSleepNative
 * Method:    DEEPSLEEP_read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_deepsleep_DeepSleepNative_DEEPSLEEP_1read
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
