/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wwc2_jni_avinsignal_AvinSignalNative */

#ifndef _Included_com_wwc2_jni_avinsignal_AvinSignalNative
#define _Included_com_wwc2_jni_avinsignal_AvinSignalNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wwc2_jni_avinsignal_AvinSignalNative
 * Method:    AVINSIGNAL_read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_avinsignal_AvinSignalNative_AVINSIGNAL_1read
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
