/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_wwc2_jni_deepsleep_DeepSleepNative.h"

/*
 * Class:     com_wwc2_jni_deepsleep_DeepSleepNative
 * Method:    DEEPSLEEP_read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_deepsleep_DeepSleepNative_DEEPSLEEP_1read
  (JNIEnv * env, jclass obj){
   jint i=3;
   return i;
   }

