/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_wwc2_jni_micswitch_MicSwitchNative.h"
/* Header for class com_wwc2_jni_micswitch_MicSwitchNative */

/*
 * Class:     com_wwc2_jni_micswitch_MicSwitchNative
 * Method:    MICSWITCH_ARM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_micswitch_MicSwitchNative_MICSWITCH_1ARM
 (JNIEnv * env, jclass obj){
  jint i=3;
  return i;
  }

/*
 * Class:     com_wwc2_jni_micswitch_MicSwitchNative
 * Method:    MICSWITCH_BT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_micswitch_MicSwitchNative_MICSWITCH_1BT
  (JNIEnv * env, jclass obj){
   jint i=3;
   return i;
   }

