/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_wwc2_jni_tp_touch_TPTouchNative.h"
/* Header for class com_wwc2_jni_tp_touch_TPTouchNative */

/*
 * Class:     com_wwc2_jni_tp_touch_TPTouchNative
 * Method:    TP_positionX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_tp_1touch_TPTouchNative_TP_1positionX
  (JNIEnv * env, jclass obj){
   jint i=8;
   return i;
   }

/*
 * Class:     com_wwc2_jni_tp_touch_TPTouchNative
 * Method:    TP_positionY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_tp_1touch_TPTouchNative_TP_1positionY
   (JNIEnv * env, jclass obj){
    jint i=8;
    return i;
    }

/*
 * Class:     com_wwc2_jni_tp_touch_TPTouchNative
 * Method:    TP_positionRect
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_jni_tp_1touch_TPTouchNative_TP_1positionRect
 (JNIEnv * env, jclass obj,jintArray array){
  jint i=8;
  return i;
  }
